// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vtjigcnunzgkoawjgvgf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0amlnY251bnpna29hd2pndmdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEzNTM2OTksImV4cCI6MjA3NjkyOTY5OX0.HjomtpRNzBgtd2RgCl_Mkndhdgh9Iy43heotdfO2N7c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});